spring.application.name=iMechanic-project-backend

# MYSQL DATABASE CONFIGURATION
spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql: true
server.port=10000
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimumIdle=1

# KEYS
# https://tools.keycdn.com/sha256-online-generator
security.jwt.key.private=
security.jwt.user.generator=

## Email configuration
spring.email.sender.host=smtp.gmail.com
spring.email.sender.debug=true
spring.email.sender.user=imechanic.serv@gmail.com
spring.email.sender.password=${PASSWORD_APP}

# Url
url.client.side=${URL_CLIENT_SIDE}
